package com.loterie.config;

public interface Privileges {
	public static final String[] PRIVILEGES = { 
			"banque-creer", "banque-supprimer", "banque-modifier-fonds", "banque-modifier-mises", 
			"banque-modifier-gains", "grille-creer", "grille-prop-supprimer", "grille-supprimer", 
			"grille-prop-modifier-nom", "grille-prop-modifier-numeros", "grille-prop-modifier-etoiles", 
			"grille-prop-modifier-etoile_plus", "grille-prop-modifier-mymillion", "grille-prop-modifier-fk_createur", 
			"grille-prop-modifier-fk_jeu_id", "grille-prop-modifier-fk_banque_id", "grille-prop-modifier-publique", 
			"grille-prop-modifier-visible", "grille-prop-modifier-active", "grille-modifier-nom", 
			"grille-modifier-numeros", "grille-modifier-etoiles", "grille-modifier-etoile_plus", 
			"grille-modifier-mymillion", "grille-modifier-fk_createur", "grille-modifier-fk_jeu_id", 
			"grille-modifier-fk_banque_id", "grille-modifier-publique", "grille-modifier-visible", 
			"grille-modifier-active", "jeu-creer", "jeu-supprimer", "jeu-modifier-nom", 
			"jeu-modifier-tirage_par_semaine", "jeu-modifier-jour_de_tirage", "jeu-modifier-prix_par_tirage", 
			"jeu-modifier-heure_validation", "jour-creer", "jour-supprimer", "jour-modifier-date_jour", 
			"jour-modifier-fk_lien_gu_id", "jour-modifier-paye", "lien_grille_utilisateur-creer", 
			"lien_grille_utilisateur-supprimer", "lien_grille_utilisateur-modifier-fk_grille_id", 
			"lien_grille_utilisateur-modifier-fk_utilisateur_id", "log-creer", "log-supprimer", "log-modifier-utc", 
			"log-modifier-jour", "log-modifier-heure", "log-modifier-niveau", "log-modifier-type", 
			"log-modifier-fk_declencheur", "log-modifier-fk_joueur_lie", "log-modifier-fk_grille_liee", 
			"log-modifier-message", "portefeuille-creer", "portefeuille-supprimer", 
			"portefeuille-modifier-date_creation", "portefeuille-modifier-fonds", "privilege-creer", 
			"privilege-supprimer", "privilege-modifier-privileges", "resultat_euromillions-creer", 
			"resultat_euromillions-modifier-numero_tirage", "resultat_euromillions-modifier-date_tirage", 
			"resultat_euromillions-modifier-boule1", "resultat_euromillions-modifier-boule2", 
			"resultat_euromillions-modifier-boule3", "resultat_euromillions-modifier-boule4", 
			"resultat_euromillions-modifier-boule5", "resultat_euromillions-modifier-etoile1", 
			"resultat_euromillions-modifier-etoile2", "resultat_euromillions-modifier-gagnant_rang1", 
			"resultat_euromillions-modifier-gains_rang1", "resultat_euromillions-modifier-gagnant_rang2", 
			"resultat_euromillions-modifier-gains_rang2", "resultat_euromillions-modifier-gagnant_rang3", 
			"resultat_euromillions-modifier-gains_rang3", "resultat_euromillions-modifier-gagnant_rang4", 
			"resultat_euromillions-modifier-gains_rang4", "resultat_euromillions-modifier-gagnant_rang5", 
			"resultat_euromillions-modifier-gains_rang5", "resultat_euromillions-modifier-gagnant_rang6", 
			"resultat_euromillions-modifier-gains_rang6", "resultat_euromillions-modifier-gagnant_rang7", 
			"resultat_euromillions-modifier-gains_rang7", "resultat_euromillions-modifier-gagnant_rang8", 
			"resultat_euromillions-modifier-gains_rang8", "resultat_euromillions-modifier-gagnant_rang9", 
			"resultat_euromillions-modifier-gains_rang9", "resultat_euromillions-modifier-gagnant_rang10", 
			"resultat_euromillions-modifier-gains_rang10", "resultat_euromillions-modifier-gagnant_rang11", 
			"resultat_euromillions-modifier-gains_rang11", "resultat_euromillions-modifier-gagnant_rang12", 
			"resultat_euromillions-modifier-gains_rang12", "resultat_euromillions-modifier-gagnant_rang13", 
			"resultat_euromillions-modifier-gains_rang13", "resultat_euromillions-modifier-mymillion", 
			"resultat_euromillions-supprimer", "retard-creer", "retard-supprimer", "retard-modifier-fk_joueur_id", 
			"retard-modifier-date_constat", "retard-modifier-date_relance", "retard-modifier-relance", 
			"utilisateur-creer", "utilisateur-supprimer", "utilisateur-prop-modifier-id", 
			"utilisateur-prop-modifier-pseudo", "utilisateur-prop-modifier-nom", "utilisateur-prop-modifier-prenom", 
			"utilisateur-prop-modifier-email", "utilisateur-prop-modifier-grain_de_sel", 
			"utilisateur-prop-modifier-mot_de_passe", "utilisateur-prop-modifier-niveau", 
			"utilisateur-prop-modifier-fk_portefeuille_id", "utilisateur-prop-modifier-fk_privilege_id", 
			"utilisateur-modifier-id", "utilisateur-modifier-pseudo", "utilisateur-modifier-nom", 
			"utilisateur-modifier-prenom", "utilisateur-modifier-email", "utilisateur-modifier-grain_de_sel", 
			"utilisateur-modifier-mot_de_passe", "utilisateur-modifier-niveau", 
			"utilisateur-modifier-fk_portefeuille_id", "utilisateur-modifier-fk_privilege_id"
		};
}
